theme: jekyll-theme-midnight
title: Manan Tomar
description: Senior Undergradratuate, IIT Madras
#avatar: https://raw.githubusercontent.com/PrekshaNema25/PrekshaNema25.github.io/master/images/preksha_image.jpg
# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: https://avatars1.githubusercontent.com/u/3407350?v=3&s=140
#avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
#Somewher://avatars1.githubusercontent.com/u/3407350?v=3&s=140
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: manan.tomar@gmail.com
  facebook:
  flickr:
  github: manantomar
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: #jekyllrb
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://manantomar.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""
