url: 'https://manantomar.github.io'
include: [CNAME]
baseurl: ''
title: 'Manan Tomar'

# # No jekyll-postcss here for CI
# plugins: []

plugins:
  - jekyll-postcss

exclude:
  - vendor
  - node_modules
  - .jekyll-cache
  - .bundle
  - Gemfile
  - Gemfile.lock
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..3
social:
  twitter: manan_tomar
  linkedin: manan-tomar-615653119
  scholar: kamjbL0AAAAJ
  github: manantomar
  email: manan.tomar@gmail.com

permalink: /blog/:title/

google_analytics: G-V96LWF8C33

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
